const tags = ["ui", "fix", "priority", "feature", "bug"];
const organizations = [
  {
    id: "O1",
    orgName: "cohort",
    members: [
      { id: "M1", name: "Amit", password: "amit", role: "super-admin" },
      { id: "M2", name: "Shivam", password: "shivam", role: "admin" },
      { id: "M3", name: "Raj", password: "raj", role: "employee" },
      { id: "M4", name: "Vineet", password: "vineet", role: "employee" },
    ],
    boards: [
      {
        id: "B1",
        boardTitle: "Pending",
        themeColor: "red",
        access: ["super-admin", "admin"],
      },
      {
        id: "B2",
        boardTitle: "In Progress",
        access: ["super-admin", "admin"],
        themeColor: "blue",
      },
      {
        id: "B3",
        boardTitle: "In Review",
        access: ["super-admin", "admin"],
        themeColor: "orange",
      },
      {
        id: "B4",
        boardTitle: "Completed",
        access: ["super-admin", "admin"],
        themeColor: "green",
      },
    ],
    boardItems: [
      {
        id: "T1",
        boardId: "B1",
        title: "Fix UI",
        description:
          "In navbar there is issue of alignment please take a look in it",
        assignedTo: "Vineet",
        assignedOn: "06/03/2025",
        dueDate: "08/03/2025",
        tags: ["ui", "fix"],
      },
      {
        id: "T2",
        boardId: "B1",
        title: "Implement Login",
        description: "Implement user login functionality",
        assignedTo: "Shivam",
        assignedOn: "06/03/2025",
        dueDate: "10/03/2025",
        tags: ["feature"],
      },
      {
        id: "T3",
        boardId: "B1",
        title: "Address Button Bug",
        description: "The button is not working",
        assignedTo: "Raj",
        assignedOn: "06/03/2025",
        dueDate: "09/03/2025",
        tags: ["bug", "fix"],
      },
      {
        id: "T4",
        boardId: "B2",
        title: "Develop Kanban Board",
        description: "Develop the main kanban board functionality",
        assignedTo: "Shivam",
        assignedOn: "05/03/2025",
        dueDate: "07/03/2025",
        tags: ["feature"],
      },
      {
        id: "T5",
        boardId: "B2",
        title: "Integrate Drag and Drop",
        description: "Integrate drag and drop functionality",
        assignedTo: "Vineet",
        assignedOn: "05/03/2025",
        dueDate: "08/03/2025",
        tags: ["feature"],
      },
      {
        id: "T6",
        boardId: "B2",
        title: "Test API Endpoints",
        description: "Test all API endpoints",
        assignedTo: "Raj",
        assignedOn: "05/03/2025",
        dueDate: "07/03/2025",
        tags: ["priority"],
      },
      {
        id: "T7",
        boardId: "B3",
        title: "Review UI Changes",
        description: "Review the latest UI changes",
        assignedTo: "Shivam",
        assignedOn: "04/03/2025",
        dueDate: "06/03/2025",
        tags: ["ui"],
      },
      {
        id: "T8",
        boardId: "B3",
        title: "Check Authentication Flow",
        description: "Check the authentication flow",
        assignedTo: "Raj",
        assignedOn: "04/03/2025",
        dueDate: "07/03/2025",
        tags: ["priority"],
      },
      {
        id: "T9",
        boardId: "B3",
        title: "Validate Data Models",
        description: "Validate the data models",
        assignedTo: "Vineet",
        assignedOn: "04/03/2025",
        dueDate: "06/03/2025",
        tags: ["priority"],
      },
      {
        id: "T10",
        boardId: "B4",
        title: "Set Up Project",
        description: "Set up the project",
        assignedTo: "Shivam",
        assignedOn: "01/03/2025",
        dueDate: "03/03/2025",
        tags: [],
      },
      {
        id: "T11",
        boardId: "B4",
        title: "Design Database Schema",
        description: "Design the database schema",
        assignedTo: "Raj",
        assignedOn: "01/03/2025",
        dueDate: "04/03/2025",
        tags: [],
      },
      {
        id: "T12",
        boardId: "B4",
        title: "Write Basic API",
        description: "Write basic API endpoints",
        assignedTo: "Vineet",
        assignedOn: "02/03/2025",
        dueDate: "05/03/2025",
        tags: [],
      },
    ],
  },
  {
    id: "O2",
    orgName: "TechCorp",
    members: [
      { id: "M5", name: "Alice", password: "alice", role: "super-admin" },
      { id: "M6", name: "Bob", password: "bob", role: "admin" },
      { id: "M7", name: "Charlie", password: "charlie", role: "employee" },
      { id: "M8", name: "David", password: "david", role: "employee" },
    ],
    boards: [
      {
        id: "B5",
        boardTitle: "Backlog",
        themeColor: "purple",
        access: ["super-admin", "admin"],
      },
      {
        id: "B6",
        boardTitle: "Sprint 1",
        access: ["super-admin", "admin"],
        themeColor: "yellow",
      },
      {
        id: "B7",
        boardTitle: "Testing",
        access: ["super-admin", "admin"],
        themeColor: "gray",
      },
      {
        id: "B8",
        boardTitle: "Deployed",
        access: ["super-admin", "admin"],
        themeColor: "teal",
      },
    ],
    boardItems: [
      {
        id: "T13",
        boardId: "B5",
        title: "Plan New Features",
        description: "Plan features for the next release",
        assignedTo: "Bob",
        assignedOn: "06/03/2025",
        dueDate: "12/03/2025",
        tags: ["feature", "priority"],
      },
      {
        id: "T14",
        boardId: "B5",
        title: "Gather User Feedback",
        description: "Collect feedback from users",
        assignedTo: "Charlie",
        assignedOn: "06/03/2025",
        dueDate: "15/03/2025",
        tags: ["ui", "feature"],
      },
      {
        id: "T15",
        boardId: "B6",
        title: "Develop Feature A",
        description: "Develop the first feature",
        assignedTo: "David",
        assignedOn: "05/03/2025",
        dueDate: "10/03/2025",
        tags: ["feature"],
      },
      {
        id: "T16",
        boardId: "B6",
        title: "Implement API Integration",
        description: "Integrate with external API",
        assignedTo: "Bob",
        assignedOn: "05/03/2025",
        dueDate: "11/03/2025",
        tags: ["feature"],
      },
      {
        id: "T17",
        boardId: "B7",
        title: "Run Unit Tests",
        description: "Run all unit tests",
        assignedTo: "Charlie",
        assignedOn: "04/03/2025",
        dueDate: "08/03/2025",
        tags: ["priority"],
      },
      {
        id: "T18",
        boardId: "B7",
        title: "Perform User Testing",
        description: "Conduct user testing sessions",
        assignedTo: "David",
        assignedOn: "04/03/2025",
        dueDate: "09/03/2025",
        tags: ["ui"],
      },
      {
        id: "T19",
        boardId: "B8",
        title: "Deploy Version 1.0",
        description: "Deploy the first version",
        assignedTo: "Bob",
        assignedOn: "01/03/2025",
        dueDate: "05/03/2025",
        tags: [],
      },
      {
        id: "T20",
        boardId: "B8",
        title: "Monitor Performance",
        description: "Monitor server performance",
        assignedTo: "Charlie",
        assignedOn: "01/03/2025",
        dueDate: "06/03/2025",
        tags: [],
      },
    ],
  },
];

function setTags(...newTags) {
  newTags.forEach((newTag) => {
    if (!tags.some((tag) => tag === newTag.toLowerCase())) {
      tags.push(newTag);
    }
  });
}

export { tags, organizations, setTags };
